name: teensy40

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '**.md'

env:
  BUILD_TYPE: Release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: download toolchain
      run: |
        curl  -L "https://developer.arm.com/-/media/Files/downloads/gnu-rm/9-2019q4/RC2.1/gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux.tar.bz2" --output /tmp/gcc-arm-none-eabi.tar.bz2
        mkdir -p /opt
        cd /opt
        tar xjf /tmp/gcc-arm-none-eabi.tar.bz2
        rm /tmp/gcc-arm-none-eabi.tar.bz2
        echo "/opt/gcc-arm-none-eabi-9-2019-q4-major/bin"

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_TOOLCHAIN_FILE="${{github.workspace}}/cmake/toolchains/teensy41.cmake"

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE --target arduino_tftpianoview_example_first

    - uses: actions/upload-artifact@v4
      with:
        name: hex file
        path: cmake-build-debug/examples/arduino_tftpianoview_example_first/arduino_tftpianoview_example_first.hex