name: Ubuntu-x64

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - 'examples/**'
      - 'docs/**'
      - '.github/workflows/teensy.yml'
env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: newdigate/teensy-x86-stubs
          path: teensy-x86-stubs

      - uses: actions/checkout@v2
        with:
          repository: newdigate/teensy-gfx
          path: teensy-gfx

      - uses: actions/checkout@v2
        with:
          repository: newdigate/midi-smf-reader
          path: midi-smf-reader

      - uses: actions/checkout@v2
        with:
          repository: newdigate/teensy-st7735-linux-stubs
          path: teensy-st7735-linux-stubs

      - name: Make and Install Dependencies
        run: |
          cd teensy-x86-stubs && mkdir cmake-build-$BUILD_TYPE && cd cmake-build-$BUILD_TYPE && cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE .. && sudo make install
          cd ../..
          cd midi-smf-reader && mkdir cmake-build-$BUILD_TYPE && cd cmake-build-$BUILD_TYPE && cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE .. && sudo make install
          cd ../..
          cd teensy-gfx && mkdir cmake-build-$BUILD_TYPE && cd cmake-build-$BUILD_TYPE && cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE .. && sudo make install
          cd ../..
          cd teensy-st7735-linux-stubs && mkdir cmake-build-$BUILD_TYPE && cd cmake-build-$BUILD_TYPE && cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE .. && sudo make install

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: cmake --build . --config $BUILD_TYPE